import type { ImportMap } from 'payload'

// Auto-generated by `pnpm payload generate:importmap`
// En proyectos con componentes admin personalizados, este archivo se auto-actualiza.
export const importMap: ImportMap = {}
